export default [
  {
    _id: "Q101",
    course: "RS101",
    title: "Rocket Propulsion Fundamentals",
    description: "Test your knowledge of basic rocket propulsion concepts.",
    points: 30,
    dueDate: "2026-05-10",
    availableFrom: "2026-03-25",
    availableUntil: "2026-06-01",
    published: true,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimitEnabled: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q101Q1",
        title: "Specific Impulse",
        type: "MULTIPLE_CHOICE",
        points: 10,
        questionText: "What does specific impulse (Isp) measure?",
        choices: [
          { _id: "Q101Q1C1", text: "Thrust per unit mass flow rate", isCorrect: true },
          { _id: "Q101Q1C2", text: "Total fuel mass consumed", isCorrect: false },
          { _id: "Q101Q1C3", text: "Chamber pressure divided by exit pressure", isCorrect: false },
          { _id: "Q101Q1C4", text: "Nozzle exit velocity", isCorrect: false },
        ],
        correctAnswer: "",
      },
      {
        _id: "Q101Q2",
        title: "Thrust Equation",
        type: "TRUE_FALSE",
        points: 10,
        questionText:
          "Thrust is equal to the product of mass flow rate and exhaust velocity plus the pressure thrust term.",
        choices: [],
        correctAnswer: "true",
      },
      {
        _id: "Q101Q3",
        title: "Propellant Type",
        type: "FILL_IN_BLANK",
        points: 10,
        questionText:
          "A rocket engine that uses liquid oxygen and liquid hydrogen is called a ___ propellant rocket.",
        choices: [],
        correctAnswer: "liquid",
      },
    ],
  },

  {
    _id: "Q102",
    course: "RS101",
    title: "Combustion and Nozzle Design",
    description: "Covers combustion chamber physics and converging-diverging nozzle design.",
    points: 40,
    dueDate: "2026-05-24",
    availableFrom: "2026-04-01",
    availableUntil: "2026-06-10",
    published: false,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: false,
    timeLimitEnabled: true,
    timeLimit: 15,
    multipleAttempts: true,
    howManyAttempts: 2,
    showCorrectAnswers: false,
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q102Q1",
        title: "De Laval Nozzle",
        type: "FILL_IN_BLANK",
        points: 10,
        questionText:
          "The converging-diverging nozzle used in rocket engines is also known as a ___ nozzle.",
        choices: [],
        correctAnswer: "De Laval",
      },
      {
        _id: "Q102Q2",
        title: "Choked Flow",
        type: "TRUE_FALSE",
        points: 10,
        questionText:
          "Flow at the nozzle throat is always supersonic in a properly operating rocket nozzle.",
        choices: [],
        correctAnswer: "false",
      },
      {
        _id: "Q102Q3",
        title: "Combustion Temperature",
        type: "MULTIPLE_CHOICE",
        points: 20,
        questionText: "Which factor most directly determines the combustion chamber temperature?",
        choices: [
          { _id: "Q102Q3C1", text: "Propellant mixture ratio", isCorrect: true },
          { _id: "Q102Q3C2", text: "Nozzle expansion ratio", isCorrect: false },
          { _id: "Q102Q3C3", text: "Chamber diameter", isCorrect: false },
          { _id: "Q102Q3C4", text: "Injector plate thickness", isCorrect: false },
        ],
        correctAnswer: "",
      },
    ],
  },

  {
    _id: "Q201",
    course: "RS102",
    title: "Aerodynamics Basics",
    description: "Fundamental concepts of aerodynamics and airfoil theory.",
    points: 35,
    dueDate: "2026-05-10",
    availableFrom: "2026-03-20",
    availableUntil: "2026-06-01",
    published: true,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimitEnabled: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q201Q1",
        title: "Lift Generation",
        type: "MULTIPLE_CHOICE",
        points: 15,
        questionText: "According to Bernoulli's principle, lift is generated because:",
        choices: [
          { _id: "Q201Q1C1", text: "Air moves faster over the upper wing surface, reducing pressure", isCorrect: true },
          { _id: "Q201Q1C2", text: "Air moves slower over the upper wing surface, increasing pressure", isCorrect: false },
          { _id: "Q201Q1C3", text: "The wing deflects air upward", isCorrect: false },
          { _id: "Q201Q1C4", text: "Gravity pulls air downward around the wing", isCorrect: false },
        ],
        correctAnswer: "",
      },
      {
        _id: "Q201Q2",
        title: "Drag Types",
        type: "TRUE_FALSE",
        points: 10,
        questionText: "Induced drag increases as the angle of attack decreases.",
        choices: [],
        correctAnswer: "false",
      },
      {
        _id: "Q201Q3",
        title: "Reynolds Number",
        type: "FILL_IN_BLANK",
        points: 10,
        questionText:
          "The dimensionless number that characterizes the ratio of inertial forces to viscous forces in a fluid is called the ___ number.",
        choices: [],
        correctAnswer: "Reynolds",
      },
    ],
  },

  {
    _id: "Q202",
    course: "RS102",
    title: "Compressible Flow and Shock Waves",
    description: "Explores supersonic flow, shock relations, and Mach number effects.",
    points: 40,
    dueDate: "2026-05-25",
    availableFrom: "2026-04-05",
    availableUntil: "2026-06-15",
    published: false,
    quizType: "PRACTICE_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimitEnabled: true,
    timeLimit: 25,
    multipleAttempts: true,
    howManyAttempts: 3,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q202Q1",
        title: "Normal Shock",
        type: "TRUE_FALSE",
        points: 10,
        questionText: "Across a normal shock wave, the flow goes from supersonic to subsonic.",
        choices: [],
        correctAnswer: "true",
      },
      {
        _id: "Q202Q2",
        title: "Mach Number",
        type: "FILL_IN_BLANK",
        points: 10,
        questionText:
          "The ratio of flow velocity to the local speed of sound is called the ___ number.",
        choices: [],
        correctAnswer: "Mach",
      },
      {
        _id: "Q202Q3",
        title: "Isentropic Flow",
        type: "MULTIPLE_CHOICE",
        points: 20,
        questionText: "In isentropic flow through a converging duct, as Mach number increases:",
        choices: [
          { _id: "Q202Q3C1", text: "Static pressure decreases", isCorrect: true },
          { _id: "Q202Q3C2", text: "Static temperature increases", isCorrect: false },
          { _id: "Q202Q3C3", text: "Total enthalpy decreases", isCorrect: false },
          { _id: "Q202Q3C4", text: "Density increases", isCorrect: false },
        ],
        correctAnswer: "",
      },
    ],
  },

  {
    _id: "Q301",
    course: "RS103",
    title: "Spacecraft Systems Overview",
    description: "Overview of spacecraft subsystems including power, thermal, and structure.",
    points: 35,
    dueDate: "2026-06-01",
    availableFrom: "2026-03-15",
    availableUntil: "2026-06-01",
    published: true,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: false,
    timeLimitEnabled: true,
    timeLimit: 20,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: false,
    webcamRequired: true,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q301Q1",
        title: "Power Systems",
        type: "MULTIPLE_CHOICE",
        points: 15,
        questionText: "Which power source is most commonly used on interplanetary spacecraft far from the Sun?",
        choices: [
          { _id: "Q301Q1C1", text: "Radioisotope thermoelectric generator (RTG)", isCorrect: true },
          { _id: "Q301Q1C2", text: "Solar panels", isCorrect: false },
          { _id: "Q301Q1C3", text: "Fuel cells", isCorrect: false },
          { _id: "Q301Q1C4", text: "Nuclear fission reactor", isCorrect: false },
        ],
        correctAnswer: "",
      },
      {
        _id: "Q301Q2",
        title: "Attitude Control",
        type: "TRUE_FALSE",
        points: 10,
        questionText: "Reaction wheels can change a spacecraft's orientation without expelling propellant.",
        choices: [],
        correctAnswer: "true",
      },
      {
        _id: "Q301Q3",
        title: "Thermal Control",
        type: "FILL_IN_BLANK",
        points: 10,
        questionText:
          "Spacecraft use ___ to radiate excess heat into space.",
        choices: [],
        correctAnswer: "radiators",
      },
    ],
  },

  {
    _id: "Q302",
    course: "RS103",
    title: "Orbital Mechanics",
    description: "Covers orbital transfer, delta-v budgets, and Hohmann transfers.",
    points: 40,
    dueDate: "2026-06-10",
    availableFrom: "2026-04-08",
    availableUntil: "2026-06-20",
    published: true,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimitEnabled: false,
    timeLimit: 30,
    multipleAttempts: false,
    howManyAttempts: 1,
    showCorrectAnswers: true,
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: true,
    questions: [
      {
        _id: "Q302Q1",
        title: "Hohmann Transfer",
        type: "TRUE_FALSE",
        points: 10,
        questionText:
          "A Hohmann transfer is the most fuel-efficient two-burn maneuver to move between two circular coplanar orbits.",
        choices: [],
        correctAnswer: "true",
      },
      {
        _id: "Q302Q2",
        title: "Orbital Velocity",
        type: "MULTIPLE_CHOICE",
        points: 20,
        questionText: "As orbital altitude increases, circular orbital velocity:",
        choices: [
          { _id: "Q302Q2C1", text: "Decreases", isCorrect: true },
          { _id: "Q302Q2C2", text: "Increases", isCorrect: false },
          { _id: "Q302Q2C3", text: "Remains the same", isCorrect: false },
          { _id: "Q302Q2C4", text: "Depends only on spacecraft mass", isCorrect: false },
        ],
        correctAnswer: "",
      },
      {
        _id: "Q302Q3",
        title: "Delta-V",
        type: "FILL_IN_BLANK",
        points: 10,
        questionText:
          "The measure of impulse per unit mass needed to perform a maneuver is called ___.",
        choices: [],
        correctAnswer: "delta-v",
      },
    ],
  },
];
